
import com.mongodb.MongoClient;
import com.mongodb.MongoCredential;
import com.mongodb.ServerAddress;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.and;
import static com.mongodb.client.model.Filters.eq;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Arrays;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ma522501
 */
public class pageConnexion extends javax.swing.JFrame {

    private boolean adminChecked;
    private pageAcceuil pa;

    /**
     * Creates new form pageConnexion
     */
    public pageConnexion() {
        initComponents();
        MongoDBConnection.connect();
        // Exclusion de sélection
        noAdmin.setSelected(true);
       
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

        ButtonGroup group = new ButtonGroup();
        group.add(yesAdmin);
        group.add(noAdmin);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pseudoField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pwField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        yesAdmin = new javax.swing.JRadioButton();
        noAdmin = new javax.swing.JRadioButton();
        createAccountButton = new javax.swing.JButton();
        connectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 250));

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 50));

        jLabel4.setText("Veuillez vous connecter ou créer un compte pour continuer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Pseudo ?");
        jPanel1.add(jLabel1);

        pseudoField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pseudoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pseudoFieldMouseClicked(evt);
            }
        });
        jPanel1.add(pseudoField);

        jLabel2.setText("Mot de passe ?");
        jPanel1.add(jLabel2);
        jPanel1.add(pwField);

        jLabel3.setText("Admin ?");
        jPanel1.add(jLabel3);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        yesAdmin.setText("Oui");
        yesAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesAdminActionPerformed(evt);
            }
        });
        jPanel3.add(yesAdmin);

        noAdmin.setText("non");
        noAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noAdminActionPerformed(evt);
            }
        });
        jPanel3.add(noAdmin);

        jPanel1.add(jPanel3);

        createAccountButton.setText("Créer un compte");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });
        jPanel1.add(createAccountButton);

        connectButton.setText("Se connecter");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        jPanel1.add(connectButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void pseudoFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pseudoFieldMouseClicked
        // TODO add your handling code here:
        pseudoField.setText("");
    }//GEN-LAST:event_pseudoFieldMouseClicked

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        creationCompte cc= new creationCompte(this);        
        cc.show();
        this.dispose();
        
        

    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
        
        String pseudo = pseudoField.getText();
        String pw = pwField.getText();
        
        if(yesAdmin.isSelected()) adminChecked = true;
        else adminChecked = false;
        
        
        if (pseudo.length() == 0 || pw.length() ==0 ){
            
            JOptionPane.showMessageDialog(this,
            "Vous devez remplir les champs pour vous connecter",
            "Champs vides",
            JOptionPane.WARNING_MESSAGE);
            
        }
        else {
            MongoDatabase db = MongoDBConnection.getDb();
            MongoCollection<Document> user = db.getCollection("user");;
            
            MongoCursor<Document> it;
            it = user.find(and(eq("pseudo" , pseudo), eq("passWord" , pw), eq("admin" , adminChecked))).iterator();

            if (it.hasNext())  
            {
                System.out.println("Connexion réussie");
                Document doc = it.next();
                int id = (int) doc.get("idA");
                
                pageAcceuil pa = new pageAcceuil(id,adminChecked);
                pa.setVisible(true);
                this.dispose();

            }
            else{ 
                
                String message;
                
                if (adminChecked) message = "Aucun administrateur ayant les informations entrées n'est présent dans la BD. \n Veuillez ré-essayer avec des identifiants corrects! ";
                else  message = "Aucun client ayant les informations entrées n'est présent dans la BD. ";
                 JOptionPane.showMessageDialog(this,
                 message,
                "Identifiants incorrects",
                JOptionPane.ERROR_MESSAGE);
                System.out.println("Echec de connexion ");
            }
          
            

            
        }
        
    }//GEN-LAST:event_connectButtonActionPerformed

    private void yesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesAdminActionPerformed
        // TODO add your handling code here:
        adminChecked=true;

    }//GEN-LAST:event_yesAdminActionPerformed

    private void noAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noAdminActionPerformed
        // TODO add your handling code here:
        adminChecked=false;

    }//GEN-LAST:event_noAdminActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pageConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pageConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pageConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pageConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pageConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectButton;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton noAdmin;
    private javax.swing.JTextField pseudoField;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JRadioButton yesAdmin;
    // End of variables declaration//GEN-END:variables
}
