
import com.mongodb.MongoClient;
import com.mongodb.MongoCredential;
import com.mongodb.ServerAddress;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Arrays;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ma522501
 */
public class pageConnexion extends javax.swing.JFrame {
    
    private boolean adminChecked;
    private pageAcceuil pa;

    /**
     * Creates new form pageConnexion
     */
    public pageConnexion() {
        initComponents();
        // Exclusion de sélection
        adminChecked=false;
        noAdmin.setSelected(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

        ButtonGroup group = new ButtonGroup();
        group.add(yesAdmin);
        group.add(noAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pseudoField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pwField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        yesAdmin = new javax.swing.JRadioButton();
        noAdmin = new javax.swing.JRadioButton();
        cancelConnectButton = new javax.swing.JButton();
        connectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 50));

        jLabel4.setText("Veuillez vous connecter pour continuer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(110, 110, 110))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Pseudo ?");
        jPanel1.add(jLabel1);

        pseudoField.setText("Entrer votre pseudo ..");
        pseudoField.setCaretColor(new java.awt.Color(0, 0, 0));
        pseudoField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pseudoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pseudoFieldMouseClicked(evt);
            }
        });
        pseudoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pseudoFieldActionPerformed(evt);
            }
        });
        jPanel1.add(pseudoField);

        jLabel2.setText("Mot de passe ?");
        jPanel1.add(jLabel2);

        pwField.setText("jPasswordField1");
        jPanel1.add(pwField);

        jLabel3.setText("Admin ?");
        jPanel1.add(jLabel3);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        yesAdmin.setText("Oui");
        yesAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesAdminActionPerformed(evt);
            }
        });
        jPanel3.add(yesAdmin);

        noAdmin.setText("non");
        noAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noAdminActionPerformed(evt);
            }
        });
        jPanel3.add(noAdmin);

        jPanel1.add(jPanel3);

        cancelConnectButton.setText("Annuler ");
        cancelConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelConnectButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelConnectButton);

        connectButton.setText("Se connecter");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        jPanel1.add(connectButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pseudoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pseudoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pseudoFieldActionPerformed

    private void pseudoFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pseudoFieldMouseClicked
        // TODO add your handling code here:
        pseudoField.setText("");
    }//GEN-LAST:event_pseudoFieldMouseClicked

    private void cancelConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelConnectButtonActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_cancelConnectButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
        
        String pseudo = pseudoField.getText();
        String pw = pwField.getText();
        
        if (pseudo.length() == 0 || pw.length() ==0 ){
            
            JOptionPane.showMessageDialog(this,
            "Vous devez remplir les champs pour vous connecter",
            "Champs vides",
            JOptionPane.WARNING_MESSAGE);
            
        }
        
        else {
            
            char [ ] pass = new char[10];
            String s="ai265149"; pass = s.toCharArray();
            MongoCredential credential = MongoCredential.createCredential("ai265149", "ai265149", pass);
            MongoClient client = new MongoClient(new ServerAddress("mongo", 27017), Arrays.asList(credential));
            MongoDatabase db = client.getDatabase("ai265149");
            
            MongoCollection<Document> collection;
            
            // cas admin 
            if (adminChecked){
                 collection = db.getCollection("admins");
            }
            // cas client 
            else{
                collection = db.getCollection("clients");
            }
            
            try (MongoCursor<Document> cursor = collection.find(new Document().append("pseudo", pseudo).append("passWord", pw)).iterator()) {
            
            if (cursor.hasNext())  
            {
                System.out.println("Connexion réussie");

                // Cas d'un administrateur 
                if (adminChecked){
                    pa = new pageAcceuil();
                }
                // Cas d'un client 
                else {
                    pa = new pageAcceuil();
                }
                
                pa.show();
                this.dispose();

            }
            else{ 
                
                String message;
                
                if (adminChecked) message = "Aucun administrateur ayant les informations entrées n'est présent dans la BD. \n Veuillez ré-essayer avec des identifiants corrects! ";
                else  message = "Aucun client ayant les informations entrées n'est présent dans la BD. ";
                 JOptionPane.showMessageDialog(this,
                message,
                "Identifiants incorrects",
                JOptionPane.ERROR_MESSAGE);
                System.out.println("Echec de connexion ");
            }
          
            }

            
        }
        
    }//GEN-LAST:event_connectButtonActionPerformed

    private void yesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesAdminActionPerformed
        // TODO add your handling code here:
        adminChecked=true;

    }//GEN-LAST:event_yesAdminActionPerformed

    private void noAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noAdminActionPerformed
        // TODO add your handling code here:
        adminChecked=false;

    }//GEN-LAST:event_noAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pageConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pageConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pageConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pageConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pageConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelConnectButton;
    private javax.swing.JButton connectButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton noAdmin;
    private javax.swing.JTextField pseudoField;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JRadioButton yesAdmin;
    // End of variables declaration//GEN-END:variables
}
