
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.eq;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.io.File;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hc047736
 */
public class presentationJeu extends javax.swing.JFrame {

    Jeu jeu;
    static int idJeu;
    /**
     * Creates new form presentationJeu
     */
    public presentationJeu(int id) {
        initComponents();
        this.idJeu = id;
        jeu = new Jeu(id);
        description();
        afficheImg();
        setAvis();
    }
    
    public void description()
    {
        MongoDBConnection.connect();
        MongoDatabase db = MongoDBConnection.getDb();
        MongoCursor<Document> it;
        MongoCollection<Document> desc = db.getCollection("description");

        it = desc.find(eq("idJeu" , this.idJeu)).iterator();
        
        Document doc = it.next();
        
        textFieldDescription.setText((String) doc.get("synopsis"));

    }
    
    public void afficheImg()
    {
        String img = jeu.getImage();
        File f = new File((String) img);

        if(f.exists() && !f.isDirectory()) panelImage.add(new JLabel(new ImageIcon(img)));
        else panelImage.add(new JLabel(new ImageIcon("imageJeux/default.png")));
        
    }
    
    public void setAvis()
    {
        MongoDBConnection.connect();
        MongoDatabase db = MongoDBConnection.getDb();
        MongoCursor<Document> it;
        MongoCollection<Document> avis = db.getCollection("Avis");

        it = avis.find(eq("idJeu" , this.idJeu)).limit(6).iterator();
        
        JPanel panel = new JPanel();
        JScrollPane scrollPane = new JScrollPane(panel);

        while (it.hasNext()) 
        {
            
            Document doc = it.next();
            JPanel jp = new JPanel(new BorderLayout());
        
            JTextArea jt = new JTextArea((String) doc.get("avis"));
            jt.setLineWrap(true);
            jp.add(jt,BorderLayout.CENTER);
            
            JLabel jl = new JLabel((String)( ""+doc.get("idUser")));
            jp.add(jl,BorderLayout.WEST);
            panel.add( jp);
        } 


panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));



panel.add(Box.createVerticalGlue());

panelAvis.add(scrollPane);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomJeu = new javax.swing.JLabel();
        corps = new javax.swing.JPanel();
        panelJeu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panelImage = new javax.swing.JPanel();
        panelLikeDislike = new javax.swing.JPanel();
        buttonLike = new javax.swing.JButton();
        buttonDislike = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelDescription = new javax.swing.JLabel();
        textFieldDescription = new javax.swing.JTextField();
        panelAvis = new javax.swing.JPanel();
        textFieldComment = new javax.swing.JTextField();
        panelJeuSimilaire = new javax.swing.JPanel();
        labelJeuSimilaire = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNomJeu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomJeu.setText("Présentation du jeu");
        labelNomJeu.setPreferredSize(new java.awt.Dimension(141, 35));
        getContentPane().add(labelNomJeu, java.awt.BorderLayout.NORTH);

        corps.setLayout(new java.awt.BorderLayout());

        panelJeu.setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelImageLayout = new javax.swing.GroupLayout(panelImage);
        panelImage.setLayout(panelImageLayout);
        panelImageLayout.setHorizontalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        panelImageLayout.setVerticalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );

        jPanel4.add(panelImage, java.awt.BorderLayout.CENTER);

        panelLikeDislike.setPreferredSize(new java.awt.Dimension(272, 40));
        panelLikeDislike.setLayout(new java.awt.BorderLayout());

        buttonLike.setText("Like");
        buttonLike.setPreferredSize(new java.awt.Dimension(94, 20));
        panelLikeDislike.add(buttonLike, java.awt.BorderLayout.WEST);

        buttonDislike.setText("Dislike");
        panelLikeDislike.add(buttonDislike, java.awt.BorderLayout.EAST);

        jPanel4.add(panelLikeDislike, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel4);

        jPanel3.setLayout(new java.awt.BorderLayout());

        labelDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescription.setText("Description du jeu :");
        labelDescription.setPreferredSize(new java.awt.Dimension(138, 35));
        jPanel3.add(labelDescription, java.awt.BorderLayout.NORTH);

        textFieldDescription.setEnabled(false);
        jPanel3.add(textFieldDescription, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        panelJeu.add(jPanel1);

        panelAvis.setLayout(new java.awt.BorderLayout());

        textFieldComment.setText("Laissez un commentaire ...");
        textFieldComment.setPreferredSize(new java.awt.Dimension(170, 25));
        panelAvis.add(textFieldComment, java.awt.BorderLayout.NORTH);

        panelJeu.add(panelAvis);

        corps.add(panelJeu, java.awt.BorderLayout.CENTER);

        panelJeuSimilaire.setLayout(new java.awt.BorderLayout());

        labelJeuSimilaire.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJeuSimilaire.setText("Jeu Similaire : ");
        labelJeuSimilaire.setPreferredSize(new java.awt.Dimension(150, 35));
        panelJeuSimilaire.add(labelJeuSimilaire, java.awt.BorderLayout.NORTH);
        panelJeuSimilaire.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        corps.add(panelJeuSimilaire, java.awt.BorderLayout.EAST);

        getContentPane().add(corps, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(presentationJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(presentationJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(presentationJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(presentationJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new presentationJeu(idJeu).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDislike;
    private javax.swing.JButton buttonLike;
    private javax.swing.JPanel corps;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelJeuSimilaire;
    private javax.swing.JLabel labelNomJeu;
    private javax.swing.JPanel panelAvis;
    private javax.swing.JPanel panelImage;
    private javax.swing.JPanel panelJeu;
    private javax.swing.JPanel panelJeuSimilaire;
    private javax.swing.JPanel panelLikeDislike;
    private javax.swing.JTextField textFieldComment;
    private javax.swing.JTextField textFieldDescription;
    // End of variables declaration//GEN-END:variables
}
